apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: rajatgupta24
    repository: jx-kubernetes-cluster
  - key: staging
  ingress:
    domain: 192.168.29.42.nip.io
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    email: rajat2411gupta@gmail.com
    username: rajatgupta24
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
